sudo: required
dist: xenial
language: node_js
node_js:
  - '11'

services:
  - xvfb

addons:
  chrome: stable # have Travis install chrome stable.

cache:
  directories:
    - node
    - node_modules

env:
  global:
    - GB_BASE=$TRAVIS_BUILD_DIR
    - TERM=dumb

before_install:
  - sudo chown root /opt/google/chrome/chrome-sandbox
  - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
  - export TZ=Europe/Amsterdam
  - date
  - export CHROME_BIN=google-chrome-stable
  - export DISPLAY=:99.0
install:
  - yarn
  - yarn package
script:
  - yarn lint
  - yarn testOnce
after_success:
  - yarn report-coverage

notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false

